# -*- coding: utf-8 -*-
# Generated by Django 2.2 on 2020-03-25 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_qiniu', '0002_bucket_https'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('token', models.TextField()),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_qiniu.Bucket')),
            ],
        ),
    ]
