# -*- coding: utf-8 -*-
# Generated by Django 2.2.9 on 2020-04-05 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_qiniu', '0003_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveBucket',
            fields=[
                ('name', models.SlugField(primary_key=True, serialize=False)),
                ('push_domain', models.CharField(max_length=127, verbose_name='直播推流域名')),
                ('play_domain_rtmp', models.CharField(max_length=127, verbose_name='直播推流域名rtmp')),
                ('play_domain_hls', models.CharField(max_length=127, verbose_name='直播推流域名hls')),
                ('play_domain_hdl', models.CharField(max_length=127, verbose_name='直播推流域名hdl')),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_qiniu.Bucket')),
            ],
        ),
    ]
