# Generated by Django 3.0.5 on 2020-04-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_qiniu', '0004_livebucket'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='_duration',
            field=models.FloatField(null=True),
        ),
    ]
